### ISSUE TITLE
Change the namespace

### ISSUE THREAD

**Issue by mpostol** [mpostol/OPCUA.Common#15]
## Goal

mpostol/ASMD#252 - remove names collision with ` CAS.CommServer.UA.Common`

## Tasks

- [x] change the assembly name
- [x] change the types used by ASMD => `OOI.OPCUA.Common.ASMD`
- [x] change the rest types
